### ISSUE TITLE
The difference with the C++ version of CannyLine？

### ISSUE THREAD

**Issue by LynnLiao** [ludlows/CannyLine#1]
hello，Is there any improvement between this version and C++'s cannyLine（https://cvrs.whu.edu.cn/cannylines/）?
Have you run the C++ version? I ran through and there was a serious memory leak; 

Lynn

**Comment by ludlows** [comment]
hi,
I don't think there is a major difference bwteen python and c++ versions.
and please propose a PR if you wanna contribute since memory leak is not a problem in this python version.
